server:
  port: 8091
  servlet:
    context-path: /api/users
management:
  server:
    port: 8190
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
    metrics:
      export:
        prometheus:
          enabled: true
          distribution:
            percentiles-histogram:
              "[http.server.requests]": true
          tags:
            application: ${PublicInfoApplication}
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: password
  liquibase:
    default-schema: users
    change-log: db/changelog/db.changelog-master.yaml
    enabled: true
    drop-first: false
  application:
    name: users
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761}
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 30


